//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRConchRepublic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConchRepublicStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConchRepublicStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRConchRepublic.ConchRepublicStrings", typeof(ConchRepublicStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airstream,Inc..
        /// </summary>
        public static string Attribution0 {
            get {
                return ResourceManager.GetString("Attribution0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber Kipp.
        /// </summary>
        public static string Attribution1 {
            get {
                return ResourceManager.GetString("Attribution1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florida Guidebook.
        /// </summary>
        public static string Attribution10 {
            get {
                return ResourceManager.GetString("Attribution10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jametlene Reskp.
        /// </summary>
        public static string Attribution11 {
            get {
                return ResourceManager.GetString("Attribution11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Johnathan Wheeler.
        /// </summary>
        public static string Attribution12 {
            get {
                return ResourceManager.GetString("Attribution12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keith Luke.
        /// </summary>
        public static string Attribution13 {
            get {
                return ResourceManager.GetString("Attribution13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mattew Mcbrayer.
        /// </summary>
        public static string Attribution14 {
            get {
                return ResourceManager.GetString("Attribution14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noel Nichols.
        /// </summary>
        public static string Attribution15 {
            get {
                return ResourceManager.GetString("Attribution15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter Pruharski.
        /// </summary>
        public static string Attribution16 {
            get {
                return ResourceManager.GetString("Attribution16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.D Smith.
        /// </summary>
        public static string Attribution17 {
            get {
                return ResourceManager.GetString("Attribution17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber Wineland.
        /// </summary>
        public static string Attribution2 {
            get {
                return ResourceManager.GetString("Attribution2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betty Subrizi.
        /// </summary>
        public static string Attribution3 {
            get {
                return ResourceManager.GetString("Attribution3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braden Egli.
        /// </summary>
        public static string Attribution4 {
            get {
                return ResourceManager.GetString("Attribution4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catherine.
        /// </summary>
        public static string Attribution5 {
            get {
                return ResourceManager.GetString("Attribution5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charles Jackson.
        /// </summary>
        public static string Attribution6 {
            get {
                return ResourceManager.GetString("Attribution6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domenick Dibenedetto-Reis.
        /// </summary>
        public static string Attribution7 {
            get {
                return ResourceManager.GetString("Attribution7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florida Guidebook.
        /// </summary>
        public static string Attribution8 {
            get {
                return ResourceManager.GetString("Attribution8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florida Guidebook.
        /// </summary>
        public static string Attribution9 {
            get {
                return ResourceManager.GetString("Attribution9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nz9i1znm32.execute-api.us-east-1.amazonaws.com/dev/getdata/.
        /// </summary>
        public static string ConchRepublicURL {
            get {
                return ResourceManager.GetString("ConchRepublicURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to airstream-inc-e4nZLI9Wbpg-unsplash.jpg.
        /// </summary>
        public static string GeneralImage0 {
            get {
                return ResourceManager.GetString("GeneralImage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amber-kipp-2kcRexKWhjU-unsplash.jpg.
        /// </summary>
        public static string GeneralImage1 {
            get {
                return ResourceManager.GetString("GeneralImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to florida-guidebook-com-xHe0i1Kqtog-unsplash.jpg.
        /// </summary>
        public static string GeneralImage10 {
            get {
                return ResourceManager.GetString("GeneralImage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jametlene-reskp-n6UGb9X3YaI-unsplash.jpg.
        /// </summary>
        public static string GeneralImage11 {
            get {
                return ResourceManager.GetString("GeneralImage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jonathan-wheeler-TkGZFU2t9gc-unsplash.jpg.
        /// </summary>
        public static string GeneralImage12 {
            get {
                return ResourceManager.GetString("GeneralImage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keith-luke-sPU2kzPIf28-unsplash.jpg.
        /// </summary>
        public static string GeneralImage13 {
            get {
                return ResourceManager.GetString("GeneralImage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matthew-mcbrayer-DxNMHyoY1tk-unsplash.jpg.
        /// </summary>
        public static string GeneralImage14 {
            get {
                return ResourceManager.GetString("GeneralImage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noel-nichols-yOMBnHVpxdg-unsplash.jpg.
        /// </summary>
        public static string GeneralImage15 {
            get {
                return ResourceManager.GetString("GeneralImage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter-pryharski-JMcoEjrm3Ro-unsplash.jpg.
        /// </summary>
        public static string GeneralImage16 {
            get {
                return ResourceManager.GetString("GeneralImage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r-d-smith-M5fmqx88VcY-unsplash.jpg.
        /// </summary>
        public static string GeneralImage17 {
            get {
                return ResourceManager.GetString("GeneralImage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amber-wineland-UERGLcd8Qug-unsplash.jpg.
        /// </summary>
        public static string GeneralImage2 {
            get {
                return ResourceManager.GetString("GeneralImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to betty-subrizi-rmpMK5rHHzU-unsplash.jpg.
        /// </summary>
        public static string GeneralImage3 {
            get {
                return ResourceManager.GetString("GeneralImage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to braden-egli-z5ficbI0QV0-unsplash.jpg.
        /// </summary>
        public static string GeneralImage4 {
            get {
                return ResourceManager.GetString("GeneralImage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catherine-nShwpLsYhpU-unsplash.jpg.
        /// </summary>
        public static string GeneralImage5 {
            get {
                return ResourceManager.GetString("GeneralImage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charles-jackson-jgQ_Luo-iRg-unsplash.jpg.
        /// </summary>
        public static string GeneralImage6 {
            get {
                return ResourceManager.GetString("GeneralImage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domenick-dibenedetto-reis-_N1r8Sc4mAg-unsplash.jpg.
        /// </summary>
        public static string GeneralImage7 {
            get {
                return ResourceManager.GetString("GeneralImage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to florida-guidebook-com-2Bdln1-BtUA-unsplash.jpg.
        /// </summary>
        public static string GeneralImage8 {
            get {
                return ResourceManager.GetString("GeneralImage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to florida-guidebook-com-HkAbnEf0Jwc-unsplash.jpg.
        /// </summary>
        public static string GeneralImage9 {
            get {
                return ResourceManager.GetString("GeneralImage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string GeneralImageCount {
            get {
                return ResourceManager.GetString("GeneralImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to islamorada-keith-luke-cropped.jpg.
        /// </summary>
        public static string IslamoradaBrochureImage {
            get {
                return ResourceManager.GetString("IslamoradaBrochureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key-largo-maja-novak-cropped.jpg.
        /// </summary>
        public static string KeyLargoBrochureImage {
            get {
                return ResourceManager.GetString("KeyLargoBrochureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywest-xHe0i1Kqtog-cropped.jpg.
        /// </summary>
        public static string KeyWestBrochureImage {
            get {
                return ResourceManager.GetString("KeyWestBrochureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower-keys-tobias-negele-cropped.jpg.
        /// </summary>
        public static string LowerKeysBrochureImage {
            get {
                return ResourceManager.GetString("LowerKeysBrochureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marathon-cropped.jpg.
        /// </summary>
        public static string MarathonBrochureImage {
            get {
                return ResourceManager.GetString("MarathonBrochureImage", resourceCulture);
            }
        }
    }
}
